//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labixa.App_Data
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Labixa.App_Data.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        #region [pioneer travel]
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản giao dịch.
        /// </summary>
        public static string AboutUs
        {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay Về.
        /// </summary>
        public static string Destination
        {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn Ảnh.
        /// </summary>
        public static string Home
        {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Mới.
        /// </summary>
        public static string HotelsDirectory
        {
            get {
                return ResourceManager.GetString("HotelsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh Sửa.
        /// </summary>
        public static string Service
        {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm Lại.
        /// </summary>
        public static string SupportOnline
        {
            get {
                return ResourceManager.GetString("SupportOnline", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Làm Lại.
        /// </summary>
        public static string CONTACTS
        {
            get
            {
                return ResourceManager.GetString("CONTACTS", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Làm Lại.
        /// </summary>
        public static string Address
        {
            get
            {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Làm Lại.
        /// </summary>
        public static string Phone
        {
            get
            {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Làm Lại.
        /// </summary>
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        public static string Solution
        {
            get
            {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        public static string Card_Process
        {
            get
            {
                return ResourceManager.GetString("Card_Process", resourceCulture);
            }
        }
        public static string Card_Gate
        {
            get
            {
                return ResourceManager.GetString("Card_Gate", resourceCulture);
            }
        }
        public static string Card_Manufacturing
        {
            get
            {
                return ResourceManager.GetString("Card_Manufacturing", resourceCulture);
            }
        }
        public static string Card_Process_detail
        {
            get
            {
                return ResourceManager.GetString("Card_Process_detail", resourceCulture);
            }
        }
        public static string Card_Gate_detail
        {
            get
            {
                return ResourceManager.GetString("Card_Gate_detail", resourceCulture);
            }
        }
        public static string Card_Manufacturing_detail
        {
            get
            {
                return ResourceManager.GetString("Card_Manufacturing_detail", resourceCulture);
            }
        }
        public static string Card_Visualization
        {
            get
            {
                return ResourceManager.GetString("Card_Visualization", resourceCulture);
            }
        }
        public static string Card_Visualization_detail
        {
            get
            {
                return ResourceManager.GetString("Card_Visualization_detail", resourceCulture);
            }
        }
        public static string Welcome
        {
            get
            {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        public static string Contact_us
        {
            get
            {
                return ResourceManager.GetString("Contact_us", resourceCulture);
            }
        }
        public static string What_We_Do
        {
            get
            {
                return ResourceManager.GetString("What_We_Do", resourceCulture);
            }
        }
        public static string Solution_Product_title
        {
            get
            {
                return ResourceManager.GetString("Solution_Product_title", resourceCulture);
            }
        }
        public static string Solution_Product_detail
        {
            get
            {
                return ResourceManager.GetString("Solution_Product_detail", resourceCulture);
            }
        }
        public static string Clients
        {
            get
            {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        public static string Projects
        {
            get
            {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
           
        public static string Feedbacks
        {
            get
            {
                return ResourceManager.GetString("Feedbacks", resourceCulture);
            }
        }  
        public static string Question_Contact_before
        {
            get
            {
                return ResourceManager.GetString("Question_Contact_before", resourceCulture);
            }
        }
        public static string Question_Contact_after
        {
            get
            {
                return ResourceManager.GetString("Question_Contact_after", resourceCulture);
            }
        }
        public static string Visit
        {
            get
            {
                return ResourceManager.GetString("Visit", resourceCulture);
            }
        }
        public static string Call
        {
            get
            {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        public static string Btn_Send_Message
        {
            get
            {
                return ResourceManager.GetString("Btn_Send_Message", resourceCulture);
            }
        }
        public static string Your_Subject
        {
            get
            {
                return ResourceManager.GetString("Your_Subject", resourceCulture);
            }
        }
        public static string Type_your_message
        {
            get
            {
                return ResourceManager.GetString("Type_your_message", resourceCulture);
            }
        }
        public static string Your_name
        {
            get
            {
                return ResourceManager.GetString("Your_name", resourceCulture);
            }
        }
        public static string Your_email
        {
            get
            {
                return ResourceManager.GetString("Your_email", resourceCulture);
            }
        }
        public static string Drop_us_message
        {
            get
            {
                return ResourceManager.GetString("Drop_us_message", resourceCulture);
            }
        }
        public static string Contact_us_email
        {
            get
            {
                return ResourceManager.GetString("Contact_us_email", resourceCulture);
            }
        }
        public static string Address_contact
        {
            get
            {
                return ResourceManager.GetString("Address_contact", resourceCulture);
            }
        }
        public static string What_we_know
        {
            get
            {
                return ResourceManager.GetString("What_we_know", resourceCulture);
            }
        }
        public static string Read_more
        {
            get
            {
                return ResourceManager.GetString("Read_more", resourceCulture);
            }
        }
        #endregion

        #region [website rise]
        public static string Home_Rise
        {
            get
            {
                return ResourceManager.GetString("Home_Rise", resourceCulture);
            }
        }
        public static string Product_Rise
        {
            get
            {
                return ResourceManager.GetString("Product_Rise", resourceCulture);
            }
        }

        //Dress_Rise
        public static string Dress_Rise
        {
            get
            {
                return ResourceManager.GetString("Dress_Rise", resourceCulture);
            }
        }
        //Shirt_Rise
        public static string Shirt_Rise
        {
            get
            {
                return ResourceManager.GetString("Shirt_Rise", resourceCulture);
            }
        }
        //Accessories_Rise
        public static string Accessories_Rise
        {
            get
            {
                return ResourceManager.GetString("Accessories_Rise", resourceCulture);
            }
        }
        //Information_Rise
        public static string Information_Rise
        {
            get
            {
                return ResourceManager.GetString("Information_Rise", resourceCulture);
            }
        }
        //Rise_News
        public static string Rise_News
        {
            get
            {
                return ResourceManager.GetString("Rise_News", resourceCulture);
            }
        }
        //Rise_Card
        public static string Rise_Card
        {
            get
            {
                return ResourceManager.GetString("Rise_Card", resourceCulture);
            }
        }
        //Rise_Footer_Description
        public static string Rise_Footer_Description
        {
            get
            {
                return ResourceManager.GetString("Rise_Footer_Description", resourceCulture);
            }
        }
        //Rise_AbouUs
        public static string Rise_AbouUs
        {
            get
            {
                return ResourceManager.GetString("Rise_AbouUs", resourceCulture);
            }
        }
        //Rise_PurchasePolicy
        public static string Rise_PurchasePolicy
        {
            get
            {
                return ResourceManager.GetString("Rise_PurchasePolicy", resourceCulture);
            }
        }
        //Rise_ReturnPolicy
        public static string Rise_ReturnPolicy
        {
            get
            {
                return ResourceManager.GetString("Rise_ReturnPolicy", resourceCulture);
            }
        }

        //Rise_TableSize
        public static string Rise_TableSize
        {
            get
            {
                return ResourceManager.GetString("Rise_TableSize", resourceCulture);
            }
        }
        //Rise_Address
        public static string Rise_Address
        {
            get
            {
                return ResourceManager.GetString("Rise_Address", resourceCulture);
            }
        }
        //Rise_AddressDetail
        public static string Rise_AddressDetail
        {
            get
            {
                return ResourceManager.GetString("Rise_AddressDetail", resourceCulture);
            }
        }
        //Rise_PhoneNumber
        public static string Rise_PhoneNumber
        {
            get
            {
                return ResourceManager.GetString("Rise_PhoneNumber", resourceCulture);
            }
        }
        //Rise_Product_new
        public static string Rise_Product_new
        {
            get
            {
                return ResourceManager.GetString("Rise_Product_new", resourceCulture);
            }
        }
        //FAVORITE_PRODUCT
        public static string FAVORITE_PRODUCT
        {
            get
            {
                return ResourceManager.GetString("FAVORITE_PRODUCT", resourceCulture);
            }
        }
        //Rise_BlogNews
        public static string Rise_BlogNews
        {
            get
            {
                return ResourceManager.GetString("Rise_BlogNews", resourceCulture);
            }
        }
        //skirt_Rise
        public static string skirt_Rise
        {
            get
            {
                return ResourceManager.GetString("skirt_Rise", resourceCulture);
            }
        }
        //Rise_about
        public static string Rise_about
        {
            get
            {
                return ResourceManager.GetString("Rise_about", resourceCulture);
            }
        }
        //Rise_Continutes
        public static string Rise_Continutes
        {
            get
            {
                return ResourceManager.GetString("Rise_Continutes", resourceCulture);
            }
        }
        //Rise_Payment
        public static string Rise_Payment
        {
            get
            {
                return ResourceManager.GetString("Rise_Payment", resourceCulture);
            }
        }
        //Rise_CardDisc
        public static string Rise_CardDisc
        {
            get
            {
                return ResourceManager.GetString("Rise_CardDisc", resourceCulture);
            }
        }
        //Rise_ Total
        public static string Rise_Total
        {
            get
            {
                return ResourceManager.GetString("Rise_Total", resourceCulture);
            }
        }
        //Rise_DeleteCard
        public static string Rise_DeleteCard
        {
            get
            {
                return ResourceManager.GetString("Rise_DeleteCard", resourceCulture);
            }
        }
        //Rise_DiscountCode
        public static string Rise_DiscountCode
        {
            get
            {
                return ResourceManager.GetString("Rise_DiscountCode", resourceCulture);
            }
        }
        //Rise_UseCode
        public static string Rise_UseCode
        {
            get
            {
                return ResourceManager.GetString("Rise_UseCode", resourceCulture);
            }
        }
        //Rise_Related
        public static string Rise_Related
        {
            get
            {
                return ResourceManager.GetString("Rise_Related", resourceCulture);
            }
        }
        //Rise_Quality
        public static string Rise_Quality
        {
            get
            {
                return ResourceManager.GetString("Rise_Quality", resourceCulture);
            }
        }
        //Rise_Confirm
        public static string Rise_Confirm
        {
            get
            {
                return ResourceManager.GetString("Rise_Confirm", resourceCulture);
            }
        }
        //Rise_paymentInfo

        public static string Rise_paymentInfo
        {
            get
            {
                return ResourceManager.GetString("Rise_paymentInfo", resourceCulture);
            }
        }
        //Rise_customInfo
        public static string Rise_customInfo
        {
            get
            {
                return ResourceManager.GetString("Rise_customInfo", resourceCulture);
            }
        }
        //Rise_Thanks

        public static string Rise_Thanks
        {
            get
            {
                return ResourceManager.GetString("Rise_Thanks", resourceCulture);
            }
        }
        //Rise_PhoneCus
        public static string Rise_PhoneCus
        {
            get
            {
                return ResourceManager.GetString("Rise_PhoneCus", resourceCulture);
            }
        }
    
        public static string Rise_NameCus
        {
            get
            {
                return ResourceManager.GetString("Rise_NameCus", resourceCulture);
            }
        }
        //Rise_Note
        public static string Rise_Note
        {
            get
            {
                return ResourceManager.GetString("Rise_Note", resourceCulture);
            }
        }
        //Rise_Order
        public static string Rise_Order
        {
            get
            {
                return ResourceManager.GetString("Rise_Order", resourceCulture);
            }
        }
        #endregion
    }
}
